HOTP/Models/AddOrg.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HOTP.Models
{
    public class AddOrg
    {
        public int GoalID { get; set; }
        public int Weight { get; set; }
        public int EmployeeID { get; set; }
        public string EmpName { get; set; }
    }

}

HOTP/Models/EvalViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HOTP.Models
{
    public class EvalViewModel
    {
        public tblHOTP_Goals Goal { get; set; }
        public int EmployeeGoalID { get; set; }
        public int EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public int Weight { get; set; }
        [Display(Name = "Item Score")]
        public decimal? ItemScore { get; set; }
        public bool CanEdit { get; set; }
        public bool Admin { get; set; }
        public bool LockCurrentFY { get; set; }
    }
}

HOTP/Models/MakeOrg.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HOTP.Models
{
    public class MakeOrg
    {
        public EvalViewModel Eval { get; set; }
        public SelectList OrgGoals { get; set; }
    }
}

HOTP/Controllers/EmployeeGoalsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HOTP.Models;

namespace HOTP.Controllers
{
    public class EmployeeGoalsController : Controller
    {
        private HOTP_Entities db = new HOTP_Entities();

        // GET: EmployeeGoals
        public ActionResult Index(int? SelectedEmp, string YearEnding)
        {
            if (SelectedEmp == null && TempData["SelectedEmp"] != null)
            {
                SelectedEmp = Convert.ToInt16(TempData["SelectedEmp"]);
            }
            var emps =
              db.tblHOTP_Employees
                .Where(s => s.Evaluations)
                .OrderBy(s => s.LastName)
                .ToList()
                .Select(s => new
                {
                    EmployeeId = s.EmployeeID,
                    FullName = string.Format("{0}, {1}", s.LastName, s.FirstName)
                });
            ViewBag.SelectedEmp = new SelectList(emps, "EmployeeID", "FullName", SelectedEmp);

            if (YearEnding == null && TempData["YearEnding"] != null)
            {
                YearEnding = TempData["YearEnding"].ToString();
            }
            TempData["YearEnding"] = YearEnding;
            ViewBag.YearEnding = PopulateCodesDDL("YearEnding", YearEnding);

            if (SelectedEmp != null)
            {
                TempData["SelectedEmp"] = SelectedEmp;
                bool editCapability = false;
                var emp = (from e in db.tblHOTP_Employees
                           where e.EmployeeID == SelectedEmp
                           select e).First();
                int supervisorID = emp.SupervisorID;
                var me = (from e in db.tblHOTP_Employees
                          where e.Email == User.Identity.Name
                          select e).First();
                if (me.Admin || ((me.EmployeeID == SelectedEmp || me.EmployeeID == supervisorID) && !emp.LockCurrentFY)) editCapability = true;
                var goals = from eg in db.tblHOTP_EmployeeGoals
                            join g in db.tblHOTP_Goals on eg.GoalID equals g.GoalID into goal
                            from subGoal in goal.DefaultIfEmpty()
                            where eg.EmployeeID == SelectedEmp && subGoal.YearEnding == YearEnding
                            select new EvalViewModel
                            {
                                Weight = eg.Weight,
                                ItemScore = eg.ItemScore,
                                EmployeeID = eg.EmployeeID,
                                EmployeeGoalID = eg.EmployeeGoalID,
                                Goal = subGoal,
                                CanEdit = editCapability,
                                Admin = me.Admin,
                                LockCurrentFY = emp.LockCurrentFY
                            };
                ViewBag.CanEdit = editCapability;
                ViewBag.Admin = me.Admin;
                return View(goals.ToList());
            }
            else
            {
                var goals = from eg in db.tblHOTP_EmployeeGoals
                            where eg.EmployeeID == 4321
                            join g in db.tblHOTP_Goals on eg.GoalID equals g.GoalID into goal
                            from subGoal in goal.DefaultIfEmpty()
                            select new EvalViewModel { Weight = eg.Weight, EmployeeID = eg.EmployeeID, Goal = subGoal };
                return View(goals.ToList());
            }
        }


        // GET: EmployeeGoals/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EvalViewModel evalViewModel = GetEvalViewModel(id);
            if (evalViewModel == null)
            {
                return HttpNotFound();
            }
            return View(evalViewModel);

        }


        // GET: EmployeeGoals/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            EvalViewModel evalViewModel = GetEvalViewModel(id);

            if (evalViewModel == null)
            {
                return HttpNotFound();
            }
            return View(evalViewModel);
        }


        // POST: EmployeeGoals/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(EvalViewModel returnedEvalViewModel)
        {
            if (ModelState.IsValid)
            {
                var goal = db.tblHOTP_Goals.Find(returnedEvalViewModel.Goal.GoalID);
                if (returnedEvalViewModel.Goal.GoalType == "Individual")
                {
                    goal.YearEnding = returnedEvalViewModel.Goal.YearEnding;
                    goal.GoalType = returnedEvalViewModel.Goal.GoalType;
                    goal.Pillar = returnedEvalViewModel.Goal.Pillar;
                    goal.GoalName = returnedEvalViewModel.Goal.GoalName;
                    goal.PillarGoalName = returnedEvalViewModel.Goal.PillarGoalName;
                    goal.Goal = returnedEvalViewModel.Goal.Goal;
                    goal.Status = returnedEvalViewModel.Goal.Status;
                    goal.ResultsMeasured = returnedEvalViewModel.Goal.ResultsMeasured;
                    goal.BestRating = returnedEvalViewModel.Goal.BestRating;
                    goal.YearEndCalculation = returnedEvalViewModel.Goal.YearEndCalculation;
                    goal.UnitsMeasuredIn = returnedEvalViewModel.Goal.UnitsMeasuredIn;
                    goal.NumDecimals = returnedEvalViewModel.Goal.NumDecimals;
                    goal.ResultsEntered = returnedEvalViewModel.Goal.ResultsEntered;
                    goal.EnteredBy = returnedEvalViewModel.Goal.EnteredBy;
                    goal.NonEditableByLeader = returnedEvalViewModel.Goal.NonEditableByLeader;
                    goal.Rating1 = returnedEvalViewModel.Goal.Rating1;
                    goal.Rating2 = returnedEvalViewModel.Goal.Rating2;
                    goal.Rating3 = returnedEvalViewModel.Goal.Rating3;
                    goal.Rating4 = returnedEvalViewModel.Goal.Rating4;
                    goal.Rating5 = returnedEvalViewModel.Goal.Rating5;
                    goal.Rating1Suffix = returnedEvalViewModel.Goal.Rating1Suffix;
                    goal.Rating2End = returnedEvalViewModel.Goal.Rating2End;
                    goal.Rating3End = returnedEvalViewModel.Goal.Rating3End;
                    goal.Rating4End = returnedEvalViewModel.Goal.Rating4End;
                    goal.Rating5Suffix = returnedEvalViewModel.Goal.Rating5Suffix;
                    goal.Jan = returnedEvalViewModel.Goal.Jan;
                    goal.Feb = returnedEvalViewModel.Goal.Feb;
                    goal.Mar = returnedEvalViewModel.Goal.Mar;
                    goal.Apr = returnedEvalViewModel.Goal.Apr;
                    goal.May = returnedEvalViewModel.Goal.May;
                    goal.Jun = returnedEvalViewModel.Goal.Jun;
                    goal.Jul = returnedEvalViewModel.Goal.Jul;
                    goal.Aug = returnedEvalViewModel.Goal.Aug;
                    goal.Sep = returnedEvalViewModel.Goal.Sep;
                    goal.Oct = returnedEvalViewModel.Goal.Oct;
                    goal.Nov = returnedEvalViewModel.Goal.Nov;
                    goal.Dec = returnedEvalViewModel.Goal.Dec;
                }
                tblHOTP_EmployeeGoals existing_EmployeeGoals = db.tblHOTP_EmployeeGoals.Find(returnedEvalViewModel.EmployeeGoalID);
                existing_EmployeeGoals.Weight = returnedEvalViewModel.Weight;
                existing_EmployeeGoals.ItemScore = Math.Round(Convert.ToDecimal(returnedEvalViewModel.Weight * goal.Score) / 100, 2);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            tblHOTP_EmployeeGoals tblHOTP_EmployeeGoals = db.tblHOTP_EmployeeGoals.Find(returnedEvalViewModel.EmployeeGoalID);
            tblHOTP_Goals tblHOTP_Goals2 = db.tblHOTP_Goals.Find(tblHOTP_EmployeeGoals.GoalID);
            tblHOTP_Employees tblHOTP_Employees = db.tblHOTP_Employees.Find(tblHOTP_EmployeeGoals.EmployeeID);
            EvalViewModel evalViewModel = new EvalViewModel
            {
                Goal = tblHOTP_Goals2,
                EmployeeGoalID = tblHOTP_EmployeeGoals.EmployeeGoalID,
                EmployeeID = tblHOTP_EmployeeGoals.EmployeeID,
                EmployeeName = tblHOTP_Employees.LastName,
                ItemScore = tblHOTP_EmployeeGoals.ItemScore,
                Weight = tblHOTP_EmployeeGoals.Weight
            };
            ViewBag.Pillar = PopulateCodesDDL("Pillar", tblHOTP_Goals2.Pillar);
            ViewBag.YearEnding = PopulateCodesDDL("YearEnding", tblHOTP_Goals2.YearEnding);
            ViewBag.ResultsMeasured = PopulateCodesDDL("ResultsMeasured", tblHOTP_Goals2.ResultsMeasured);
            ViewBag.BestRating = PopulateCodesDDL("BestRating", tblHOTP_Goals2.BestRating);
            ViewBag.YearEndCalculation = PopulateCodesDDL("YearEndCalculation", tblHOTP_Goals2.YearEndCalculation);
            ViewBag.UnitsMeasuredIn = PopulateCodesDDL("UnitsMeasuredIn", tblHOTP_Goals2.UnitsMeasuredIn);
            ViewBag.ResultsEntered = PopulateCodesDDL("ResultsEntered", tblHOTP_Goals2.ResultsEntered);
            return View(evalViewModel);
        }


        // GET: EmployeeGoals/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

HOTP/Views/EmployeeGoals/AddOrg.cshtml
@model HOTP.Models.AddOrg

@{
    ViewBag.Title = "Add Org Goal";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Add Org Goal</h2>

<h4>@Html.Display("EmpName")</h4>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        @*@Html.Hidden("EmployeeID")*@
        @Html.HiddenFor(model => model.EmployeeID)

        <div class="row">
            <div class="form-group">
                @Html.Label("Weight:", htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-1">
                    @Html.TextBox("Weight", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Weight, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.GoalID, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-4">
                    @Html.DropDownListFor(model => model.GoalID, ViewBag.GoalID as IEnumerable<SelectListItem>, null, htmlAttributes: new { @class = "form-control ratingCalc " })
                    @Html.ValidationMessageFor(model => model.GoalID, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>


<script type="text/javascript">
    $(document).ready(function () {
        $('#Weight').keypress(function (event) {
            if ((event.which < 48 || event.which > 57)) {
                event.preventDefault();
            }
        });
    });
</script>

HOTP/Views/EmployeeGoals/Delete.cshtml
@model HOTP.Models.EvalViewModel

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Remove Goal</h2>
<div class="lead">
    Org goals are removed only for this employee.
    Individual goals are deleted.
</div>
<h3>Are you sure you want to remove/delete this goal?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Weight)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Weight)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Goal.PillarGoalName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Goal.PillarGoalName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Goal.YearEnding)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Goal.YearEnding)
        </dd>


        <dt>
            @Html.DisplayNameFor(model => model.EmployeeName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmployeeName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Goal.YearEnding)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Goal.YearEnding)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Remove" class="btn btn-default" /> |
            @Html.ActionLink("Back to List (don't remove)", "Index")
        </div>
    }
</div>

HOTP/Views/EmployeeGoals/EvalReport.cshtml
@model List<HOTP.Models.EvalViewModel>

@{
    ViewBag.Title = "All";
    Layout = "~/Views/Shared/_LayoutNoHeading.cshtml";
}
<style>
    #theRest {
        font-size: 10px;
    }

    .body-content {
        margin-top: 0px;
        padding-left: 0px;
        padding-right: 0px;
    }

    select {
        font-size: medium;
    }

    .noBox {
        border: none 0px;
    }

    .weightInput input {
        width: 35px;
    }

    .score {
        width: 55px;
        font-size: 12px;
    }

    .rating {
        width: 25px;
        font-size: 12px;
        margin: 2px 0px 0px 0px;
        padding: 0px 0px 0px 0px;
        background-color: #DCECEF;
        vertical-align: baseline;
    }

    #ratingTable td {
        font-size: 13px;
        border-top: none 0px;
        margin: 0px 0px 0px 0px;
        padding: 0px 0px 0px 0px;
    }

    .writeTrue {
        font-size: 12px;
    }

    .writeFalse, .Org {
        font-size: 12px;
        width: 45px;
        background-color: #DCECEF;
    }

    .writeFalse2 {
        width: 55px;
        background-color: #DCECEF;
    }

    .white {
        font-size: 12px;
        background-color: white;
    }

    .myLabel {
        font-size: 12px;
        font-weight: bold;
    }

    .Individual {
        width: 50px;
        background-color: lemonchiffon;
    }

    .Organizational {
        width: 40px;
        background-color: #DCECEF;
    }

    .ratingNum {
        font-size: large;
        font-weight: bold;
        padding-left: 8px;
        padding-right: 4px;
    }

    .topCurve {
        border-top-left-radius: 0px;
        border-top-right-radius: 0px;
        padding: 4px 4px 4px 8px;
        margin-right: 12px;
        font-size: 13px;
        background-color: #51a1ad;
        color: white;
        font-weight: normal;
        text-align: left;
    }

    .bottomCurve {
        border-bottom-left-radius: 0px;
        border-bottom-right-radius: 0px;
        padding: 4px 4px 4px 8px;
        margin-right: 12px;
        font-size: 11px;
        margin-top: 0px;
        background-color: cornsilk;
    }

    .highlightScore {
        font-weight: bold;
        text-decoration: underline;
    }

    @@media print {
        #rptOptions {
            display: none !important;
        }
    }
</style>


<div id="rptOptions">
    <a href="javascript:history.back()">[Go Back]</a>
    &nbsp;&nbsp;
    <a href="javascript:window.print()">[Print]</a>
</div>
<h4>&nbsp;&nbsp;&nbsp;Annual Evaluation for @ViewBag.EmpName<span class="pull-right" style="font-size:small; margin-right:32px;">@DateTime.Now</span></h4>
<div class="" style="font-size:medium;">
    &nbsp;&nbsp;&nbsp;
    Overall score <input type="text" id="overallScore" class="noBox" />
</div>


<div id="theRest">


    @using (Html.BeginForm("Eval", "EmployeeGoals", FormMethod.Post, new { id = "dataForm" }))
    {

        @Html.AntiForgeryToken()

        <input type="hidden" id="scoreFrom" value="Eval" />

        <table class="table">
            @for (int i = 0; i < Model.Count; i++)
            {

                <tr>
                    <td>
                        @if (i == 0)
                        {
                            @Html.Hidden("CanEdit", Model[i].CanEdit)
                        }

                        @Html.Hidden("MyGoals.Index", (@i))
                        @Html.Hidden("MyGoals[" + (@i) + "].EmployeeID", Model[i].EmployeeID)
                        @Html.Hidden("MyGoals[" + (@i) + "].EmployeeGoalID", Model[i].EmployeeGoalID)
                        @Html.Hidden("MyGoals[" + (@i) + "].Goal.GoalID", Model[i].Goal.GoalID)
                        <div style="font-size:medium">
                            <strong>
                                @Html.DisplayFor(modelItem => Model[i].Goal.PillarGoalName)
                            </strong>
                            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                            @Html.DisplayFor(modelItem => Model[i].Weight)%
                        </div>
                        <div style="font-size:small;margin-top:8px;">
                            Result is @Html.DisplayFor(model => model[i].Goal.Result) using '@Html.DisplayFor(model => model[i].Goal.YearEndCalculation)' scoring method
                            <br />
                            Score:@Html.DisplayFor(model => model[i].Goal.Score)
                            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                            Weighted Score:
                            @Html.TextBox("MyGoals[" + (@i) + "].ItemScore", Model[i].ItemScore, new { @class = "noBox writeFalse2 myLabel itemScore", @readonly = "readonly" })
                            <div style="margin-top:8px;">
                                Goal:
                                @Html.DisplayFor(modelItem => Model[i].Goal.Goal)
                            </div>
                        </div>
                        <div style="font-size:small;margin-top:8px;">
                            @if (Model[i].Goal.JanScore != null)
                            {
                                @:Jan:@Html.DisplayFor(model => model[i].Goal.JanScore)&nbsp;&nbsp;&nbsp;&nbsp;
                                            }
                            @if (Model[i].Goal.FebScore != null)
                            {
                                @:Feb:@Html.DisplayFor(model => model[i].Goal.FebScore)&nbsp;&nbsp;&nbsp;&nbsp;
                                            }
                            @if (Model[i].Goal.MarScore != null)
                            {
                                @:Mar:@Html.DisplayFor(model => model[i].Goal.MarScore)&nbsp;&nbsp;&nbsp;&nbsp;
                                            }
                            @if (Model[i].Goal.AprScore != null)
                            {
                                @:Apr:@Html.DisplayFor(model => model[i].Goal.AprScore)&nbsp;&nbsp;&nbsp;&nbsp;
                                            }
                            @if (Model[i].Goal.MayScore != null)
                            {
                                @:May:@Html.DisplayFor(model => model[i].Goal.MayScore)&nbsp;&nbsp;&nbsp;&nbsp;
                                            }
                            @if (Model[i].Goal.JunScore != null)
                            {
                                @:Jun:@Html.DisplayFor(model => model[i].Goal.JunScore)&nbsp;&nbsp;&nbsp;&nbsp;
                                            }
                            @if (Model[i].Goal.JulScore != null)
                            {
                                @:Jul:@Html.DisplayFor(model => model[i].Goal.JulScore)&nbsp;&nbsp;&nbsp;&nbsp;
                                            }
                            @if (Model[i].Goal.AugScore != null)
                            {
                                @:Aug:@Html.DisplayFor(model => model[i].Goal.AugScore)&nbsp;&nbsp;&nbsp;&nbsp;
                                            }
                            @if (Model[i].Goal.SepScore != null)
                            {
                                @:Sep:@Html.DisplayFor(model => model[i].Goal.SepScore)&nbsp;&nbsp;&nbsp;&nbsp;
                                            }
                            @if (Model[i].Goal.OctScore != null)
                            {
                                @:Oct:@Html.DisplayFor(model => model[i].Goal.OctScore)&nbsp;&nbsp;&nbsp;&nbsp;
                                            }
                            @if (Model[i].Goal.NovScore != null)
                            {
                                @:Nov:@Html.DisplayFor(model => model[i].Goal.NovScore)&nbsp;&nbsp;&nbsp;&nbsp;
                                            }
                            @if (Model[i].Goal.DecScore != null)
                            {
                                @:Dec:@Html.DisplayFor(model => model[i].Goal.DecScore)
                                }
                        </div>
                    </td>
                    <td style="width:30%">
                        <div style="font-size:small">
                            @if (Model[i].Goal.Score == 5)
                            {
                                <span class="highlightScore">
                                    5
                                    =@Html.DisplayFor(model => model[i].Goal.Rating5) to @Html.DisplayFor(model => model[i].Goal.Rating5Suffix)
                                </span>
                            }
                            else
                            {
                                <span>
                                    5
                                    =@Html.DisplayFor(model => model[i].Goal.Rating5) to @Html.DisplayFor(model => model[i].Goal.Rating5Suffix)
                                </span>
                            }
                            <br />
                            @if (Model[i].Goal.Score == 4)
                            {
                                <span class="highlightScore">
                                    4
                                    = @Html.DisplayFor(model => model[i].Goal.Rating4) to @Html.DisplayFor(model => model[i].Goal.Rating4End)
                                </span>
                            }
                            else
                            {
                                <span>
                                    4
                                    = @Html.DisplayFor(model => model[i].Goal.Rating4) to @Html.DisplayFor(model => model[i].Goal.Rating4End)
                                </span>
                            }

                            <br />
                            @if (Model[i].Goal.Score == 3)
                            {
                                <span class="highlightScore">
                                    3
                                    = @Html.DisplayFor(model => model[i].Goal.Rating3) to @Html.DisplayFor(model => model[i].Goal.Rating3End)
                                </span>
                            }
                            else
                            {
                                <span>
                                    3
                                    = @Html.DisplayFor(model => model[i].Goal.Rating3) to @Html.DisplayFor(model => model[i].Goal.Rating3End)
                                </span>
                            }

                            <br />
                            @if (Model[i].Goal.Score == 2)
                            {
                                <span class="highlightScore">
                                    2
                                    = @Html.DisplayFor(model => model[i].Goal.Rating2) to @Html.DisplayFor(model => model[i].Goal.Rating2End)
                                </span>
                            }
                            else
                            {
                                <span>
                                    2
                                    = @Html.DisplayFor(model => model[i].Goal.Rating2) to @Html.DisplayFor(model => model[i].Goal.Rating2End)
                                </span>
                            }

                            <br />
                            @if (Model[i].Goal.Score == 1)
                            {
                                <span class="highlightScore">
                                    1
                                    = @Html.DisplayFor(model => model[i].Goal.Rating1) to @Html.DisplayFor(model => model[i].Goal.Rating1Suffix)
                                </span>
                            }
                            else
                            {
                                <span>
                                    1
                                    = @Html.DisplayFor(model => model[i].Goal.Rating1) to @Html.DisplayFor(model => model[i].Goal.Rating1Suffix)
                                </span>
                            }

                        </div>

                    </td>
                </tr>
            }
        </table>

    }


</div>

<script>
    //document.getElementById("SelectedEmp").onchange = function () {
    //    $('#loadingImage').toggle();
    //    document.getElementById("filterForm").submit();
    //};
    //document.getElementById("YearEnding").onchange = function () {
    //    $('#loadingImage').toggle();
    //    document.getElementById("filterForm").submit();
    //};
    $(document).ready(function () {
        $("#overallScore").attr('readonly', true);
        var totalOverall = parseFloat(0.00);
        $('.itemScore').each(function () {
            var thisScore = parseFloat($(this).val());
            totalOverall += thisScore;
        });
        $('#overallScore').val(Math.round(totalOverall * 100) / 100);
        var x = document.getElementById('CanEdit').value;
        if (x == 'False') {
            $("#dataForm :input").attr("disabled", true);
        }
        if ($('#SelectedEmp').val() == "") $("#theRest").hide();
        else $("#theRest").show();
    });
</script>

<script src="~/Scripts/scoreCalc.js"></script>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}