HOTP/Models/Plan90.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HOTP.Models
{
    public class Plan90ViewModel
    {
        public string EmployeeName { get; set; }
        public int EmployeeGoalID {get;set;}
        public int Weight { get; set; }
        public decimal? ItemScore { get; set; }
        public tblHOTP_Goals Goal { get; set; }
        public tblHOTP_Plan90 Plan { get; set; }
        public List<tblHOTP_ActionSteps> ActionSteps { get; set; }

    }
}

HOTP/Controllers/Plan90Controller.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HOTP.Models;
using System.IO;
//using RazorPDF;
using iTextSharp;
using iTextSharp.text;
using iTextSharp.text.pdf;
using System.Xml;
using System.Text;


namespace HOTP.Controllers
{
    public class Plan90Controller : Controller
    {
        private HOTP_Entities db = new HOTP_Entities();

        // GET: Plan90ViewModel
        public ActionResult Index(int? SelectedEmp, string YearEnding)
        {
            if (SelectedEmp == null && TempData["SelectedEmp"] != null)
            {
                SelectedEmp = Convert.ToInt16(TempData["SelectedEmp"]);
            }
            var emps =
              db.tblHOTP_Employees
                .Where(s => s.Evaluations)
                .OrderBy(s => s.LastName)
                .ToList()
                .Select(s => new
                {
                    EmployeeId = s.EmployeeID,
                    FullName = string.Format("{0}, {1}", s.LastName, s.FirstName)
                });
            ViewBag.SelectedEmp = new SelectList(emps, "EmployeeID", "FullName", SelectedEmp);

            if (YearEnding == null && TempData["YearEnding"] != null)
            {
                YearEnding = TempData["YearEnding"].ToString();
            }
            TempData["YearEnding"] = YearEnding;
            ViewBag.YearEnding = PopulateCodesDDL("YearEnding", YearEnding);

            if (SelectedEmp != null)
            {
                TempData["SelectedEmp"] = SelectedEmp;

                bool editCapability = false;
                int supervisorID = (from e in db.tblHOTP_Employees
                                    where e.EmployeeID == SelectedEmp
                                    select e.SupervisorID).First();
                var me = (from e in db.tblHOTP_Employees
                          where e.Email == User.Identity.Name
                          select e).First();
                if (me.Admin || me.EmployeeID == SelectedEmp || me.EmployeeID == supervisorID) editCapability = true;

                var goals = from eg in db.tblHOTP_EmployeeGoals
                            join g in db.tblHOTP_Goals on eg.GoalID equals g.GoalID into goal
                            from subGoal in goal.DefaultIfEmpty()
                            where eg.EmployeeID == SelectedEmp && subGoal.YearEnding == YearEnding
                            select new EvalViewModel
                            {
                                Weight = eg.Weight,
                                ItemScore = eg.ItemScore,
                                EmployeeID = eg.EmployeeID,
                                EmployeeGoalID = eg.EmployeeGoalID,
                                Goal = subGoal,
                                CanEdit = editCapability,
                                Admin = me.Admin
                            };
                return View(goals.ToList());
            }
            else
            {
                var goals = from eg in db.tblHOTP_EmployeeGoals
                            where eg.EmployeeID == 4321
                            join g in db.tblHOTP_Goals on eg.GoalID equals g.GoalID into goal
                            from subGoal in goal.DefaultIfEmpty()
                            select new EvalViewModel { Weight = eg.Weight, EmployeeID = eg.EmployeeID, Goal = subGoal };
                return View(goals.ToList());
            }
        }


        // GET: Plan90ViewModel/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PopulatePlan(id);
            tblHOTP_EmployeeGoals employeeGoal = db.tblHOTP_EmployeeGoals.Find(id);
            //var goal = db.tblHOTP_Goals.Find(employeeGoal.GoalID);
            tblHOTP_Employees employee = db.tblHOTP_Employees.Find(employeeGoal.EmployeeID);

            var plans = from p in db.tblHOTP_Plan90
                        where p.EmployeeGoalID == id
                        join eg in db.tblHOTP_EmployeeGoals on p.EmployeeGoalID equals eg.EmployeeGoalID into empGoal
                        from subEmployeeGoal in empGoal.DefaultIfEmpty()
                        join g in db.tblHOTP_Goals on employeeGoal.GoalID equals g.GoalID into goal
                        from subGoal in goal.DefaultIfEmpty()
                        select new Plan90ViewModel
                        {
                            EmployeeName = employee.FirstName + " " + employee.LastName,
                            EmployeeGoalID = employeeGoal.EmployeeGoalID,
                            Weight = employeeGoal.Weight,
                            ItemScore = employeeGoal.ItemScore,
                            Goal = subGoal,
                            Plan = p,
                            ActionSteps = db.tblHOTP_ActionSteps.Where(a => a.PlanID == p.PlanID).ToList()
                        };
            ViewBag.PlanStatus = PopulateCodesDDL("PlanStatus");
            return View(plans.ToList());
        }


        // GET: Plan90ViewModel/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PopulatePlan(id);
            tblHOTP_EmployeeGoals employeeGoal = db.tblHOTP_EmployeeGoals.Find(id);
            //var goal = db.tblHOTP_Goals.Find(employeeGoal.GoalID);
            tblHOTP_Employees employee = db.tblHOTP_Employees.Find(employeeGoal.EmployeeID);

            var plans = from p in db.tblHOTP_Plan90
                        where p.EmployeeGoalID == id
                        join eg in db.tblHOTP_EmployeeGoals on p.EmployeeGoalID equals eg.EmployeeGoalID into empGoal
                        from subEmployeeGoal in empGoal.DefaultIfEmpty()
                        join g in db.tblHOTP_Goals on employeeGoal.GoalID equals g.GoalID into goal
                        from subGoal in goal.DefaultIfEmpty()
                        select new Plan90ViewModel
                        {
                            EmployeeName = employee.FirstName + " " + employee.LastName,
                            EmployeeGoalID = employeeGoal.EmployeeGoalID,
                            Weight = employeeGoal.Weight,
                            ItemScore = employeeGoal.ItemScore,
                            Goal = subGoal,
                            Plan = p,
                            ActionSteps = db.tblHOTP_ActionSteps.Where(a => a.PlanID == p.PlanID).ToList()
                        };
            ViewBag.PlanStatus = PopulateCodesDDL("PlanStatus");
            return View(plans.ToList());
        }


        public void PopulatePlan(int? id)
        {
            var plans = from p in db.tblHOTP_Plan90
                        where p.EmployeeGoalID == id
                        select p.PlanID;
            if (plans.Count() > 0)
                return;
            for (int quarter = 1; quarter < 5; quarter++)
            {
                tblHOTP_Plan90 newPlan = new tblHOTP_Plan90();
                newPlan.EmployeeGoalID = Convert.ToInt16(id);
                newPlan.Quarter = quarter;
                newPlan.Goal = "";
                db.tblHOTP_Plan90.Add(newPlan);
                db.SaveChanges();
                int planID = newPlan.PlanID;
                tblHOTP_ActionSteps actionStep = new tblHOTP_ActionSteps();
                actionStep.PlanID = planID;
                actionStep.ActionStep = "";
                actionStep.Result = "";
                actionStep.Status = "";
                db.tblHOTP_ActionSteps.Add(actionStep);
                db.SaveChanges();
            }
        }



        // POST: Plan90ViewModel/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(List<Plan90ViewModel> MyPlans)
        //public ActionResult Edit([Bind(Include = "PlanID,EmployeeGoalID,Quarter,Goal")] tblHOTP_Plan90 tblHOTP_Plan90)
        {
            if (ModelState.IsValid)
            {
                foreach (Plan90ViewModel plan90 in MyPlans)
                {
                    tblHOTP_Plan90 existingPlan = db.tblHOTP_Plan90.Find(plan90.Plan.PlanID);
                    existingPlan.Goal = plan90.Plan.Goal;
                    foreach (tblHOTP_ActionSteps actionStep in plan90.ActionSteps)
                    {
                        if (actionStep.ActionID != 99999 && actionStep.Status == "Remove")
                        {
                            tblHOTP_ActionSteps existingAction = db.tblHOTP_ActionSteps.Find(actionStep.ActionID);
                            db.tblHOTP_ActionSteps.Remove(existingAction);
                        }
                        else
                            if (actionStep.ActionID == 99999 && actionStep.Status != "Remove")
                            {
                                tblHOTP_ActionSteps newActionStep = new tblHOTP_ActionSteps();
                                newActionStep.PlanID = plan90.Plan.PlanID;
                                newActionStep.ActionStep = actionStep.ActionStep;
                                newActionStep.Result = actionStep.Result;
                                newActionStep.Status = actionStep.Status;
                                db.tblHOTP_ActionSteps.Add(newActionStep);
                            }
                            else
                            {
                                if (actionStep.ActionID != 99999)
                                {

HOTP/Views/Plan90/Create.cshtml
@model HOTP.Models.tblHOTP_Plan90

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>tblHOTP_Plan90</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.EmployeeGoalID, "EmployeeGoalID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("EmployeeGoalID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.EmployeeGoalID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Quarter, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Quarter, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Quarter, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Goal, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Goal, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Goal, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

HOTP/Views/Plan90/Delete.cshtml
@model HOTP.Models.tblHOTP_Plan90

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>tblHOTP_Plan90</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Quarter)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quarter)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Goal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Goal)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tblHOTP_EmployeeGoals.IndNotes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tblHOTP_EmployeeGoals.IndNotes)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

HOTP/Views/Plan90/Details.cshtml
@model List<HOTP.Models.Plan90ViewModel>

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    textarea {
        border: 1px solid lightgray;
        border-radius: 5px;
        padding: 4px 4px 4px 4px;
        margin-right: 12px;
        margin-bottom: 4px;
    }

    .noBoxStop {
        border: none;
    }

    .nav-tabs > li > a {
        font-size: 16px;
    }

    .highlightScore {
        background-color: yellow;
    }

    .topCurve {
        border-top-left-radius: 5px;
        border-top-right-radius: 5px;        
        margin-right: 12px;
        font-size:large;
        background-color:#51a1ad; 
        color:white; 
        font-weight:normal; 
        text-align:left; 
        padding:4px 4px 4px 8px;
    }

    .bottomCurve {
        border-bottom-left-radius: 5px;
        border-bottom-right-radius: 5px;
        margin-right: 12px;
        font-size:14px;
        padding:4px 4px 4px 8px; 
        margin-top:0px;
        background-color: cornsilk;
    }

</style>
<h3>90-Day Action Plan for @Model[0].EmployeeName</h3>

<div id="theRest">

    @using (Html.BeginForm(null, null, FormMethod.Post, new { id = "displayForm" }))
    {
        @Html.AntiForgeryToken()

        <div class="row" style="margin-bottom:8px;">
            <div class="col-md-12">
                @Html.Hidden("MyPlans[0].EmployeeGoalID", Model[0].EmployeeGoalID)
                @Html.Hidden("MyPlans[0].PillarGoalName", Model[0].Goal.PillarGoalName)
                @Html.Hidden("MyPlans[0].Weight", Model[0].Weight)
                @Html.Hidden("MyPlans[0].EmployeeGoal", Model[0].Goal.Goal)

                <div class="row" style="margin-bottom:8px;">
                    <div class="col-md-12">
                        <div class="topCurve">
                            @Html.DisplayFor(model => model[0].Goal.PillarGoalName)
                            &nbsp;|&nbsp;
                            @Html.DisplayFor(model => model[0].Weight)%
                            <div style="font-size:medium; ">
                                @Html.DisplayFor(model => model[0].Goal.Goal)
                            </div>
                        </div>
                        <div class="bottomCurve">
                            @if (Model[0].Goal.Score == 5)
                            {
                                <span class="highlightScore">5</span>
                            }
                            else
                            {
                                <span>5</span>
                            }
                            =@Html.DisplayFor(model => model[0].Goal.Rating5) to @Html.DisplayFor(model => model[0].Goal.Rating5Suffix)
                            &nbsp;&bull;&nbsp;
                            @if (Model[0].Goal.Score == 4)
                            {
                                <span class="highlightScore">4</span>
                            }
                            else
                            {
                                <span>4</span>
                            }
                            = @Html.DisplayFor(model => model[0].Goal.Rating4) to @Html.DisplayFor(model => model[0].Goal.Rating4End)
                            &nbsp;&bull;&nbsp;
                            @if (Model[0].Goal.Score == 3)
                            {
                                <span class="highlightScore">3</span>
                            }
                            else
                            {
                                <span>3</span>
                            }
                            = @Html.DisplayFor(model => model[0].Goal.Rating3) to @Html.DisplayFor(model => model[0].Goal.Rating3End)
                            &nbsp;&bull;&nbsp;
                            @if (Model[0].Goal.Score == 2)
                            {
                                <span class="highlightScore">2</span>
                            }
                            else
                            {
                                <span>2</span>
                            }
                            = @Html.DisplayFor(model => model[0].Goal.Rating2) to @Html.DisplayFor(model => model[0].Goal.Rating2End)
                            &nbsp;&bull;&nbsp;
                            @if (Model[0].Goal.Score == 1)
                            {
                                <span class="highlightScore">1</span>
                            }
                            else
                            {
                                <span>1</span>
                            }
                            = @Html.DisplayFor(model => model[0].Goal.Rating1) to @Html.DisplayFor(model => model[0].Goal.Rating1Suffix)
                            &nbsp;&bull;&nbsp;
                            Result is @Html.DisplayFor(model => model[0].Goal.Result) using scoring method: @Html.DisplayFor(model => model[0].Goal.YearEndCalculation)
                            <br />
                            @if (Model[0].Goal.JanScore != null)
                            {
                                @:Jan:@Html.DisplayFor(model => model[0].Goal.JanScore)&nbsp;&bull;&nbsp;
                                            }
                            @if (Model[0].Goal.FebScore != null)
                            {
                                @:Feb:@Html.DisplayFor(model => model[0].Goal.FebScore)&nbsp;&bull;&nbsp;
                                            }
                            @if (Model[0].Goal.MarScore != null)
                            {
                                @:Mar:@Html.DisplayFor(model => model[0].Goal.MarScore)&nbsp;&bull;&nbsp;
                                            }
                            @if (Model[0].Goal.AprScore != null)
                            {
                                @:Apr:@Html.DisplayFor(model => model[0].Goal.AprScore)&nbsp;&bull;&nbsp;
                                            }
                            @if (Model[0].Goal.MayScore != null)
                            {
                                @:May:@Html.DisplayFor(model => model[0].Goal.MayScore)&nbsp;&bull;&nbsp;
                                            }
                            @if (Model[0].Goal.JunScore != null)
                            {
                                @:Jun:@Html.DisplayFor(model => model[0].Goal.JunScore)&nbsp;&bull;&nbsp;
                                            }
                            @if (Model[0].Goal.JulScore != null)
                            {
                                @:Jul:@Html.DisplayFor(model => model[0].Goal.JulScore)&nbsp;&bull;&nbsp;
                                            }
                            @if (Model[0].Goal.AugScore != null)
                            {
                                @:Aug:@Html.DisplayFor(model => model[0].Goal.AugScore)&nbsp;&bull;&nbsp;
                                            }
                            @if (Model[0].Goal.SepScore != null)
                            {
                                @:Sep:@Html.DisplayFor(model => model[0].Goal.SepScore)&nbsp;&bull;&nbsp;
                                            }
                            @if (Model[0].Goal.OctScore != null)
                            {
                                @:Oct:@Html.DisplayFor(model => model[0].Goal.OctScore)&nbsp;&bull;&nbsp;
                                            }
                            @if (Model[0].Goal.NovScore != null)
                            {
                                @:Nov:@Html.DisplayFor(model => model[0].Goal.NovScore)&nbsp;&bull;&nbsp;
                                            }
                            @if (Model[0].Goal.DecScore != null)
                            {
                                @:Dec:@Html.DisplayFor(model => model[0].Goal.DecScore)
                                            }
                        </div>

                    </div>
                </div>
            </div>
        </div>
                            int month = System.DateTime.Now.Month;
                            int activeQuarter = 1;
                            string q1c = "quarterTabs";
                            string q2c = "quarterTabs";
                            string q3c = "quarterTabs";
                            string q4c = "quarterTabs";
                            if (month > 9) { q4c = "active"; activeQuarter = 4; }
                            else if (month > 6) { q3c = "active"; activeQuarter = 3; }
                            else if (month > 3) { q2c = "active"; activeQuarter = 2; }
                            else { q1c = "active"; }

        <ul class="nav nav-tabs" style="font-size:16px;">
            <li class="@q1c"><a data-toggle="tab" href="#quarter1">Quarter 1</a></li>
            <li class="@q2c"><a data-toggle="tab" href="#quarter2">Quarter 2</a></li>
            <li class="@q3c"><a data-toggle="tab" href="#quarter3">Quarter 3</a></li>
            <li class="@q4c"><a data-toggle="tab" href="#quarter4">Quarter 4</a></li>
        </ul>

        <div class="tab-content" style="border:1px solid lightgray; border-top:none; padding:8px 8px 8px 8px">

            @for (int i = 0; i < Model.Count; i++)
            {
                int thisQ = i + 1;
                string quarterID = "quarter" + thisQ;
                string planID = Model[i].Plan.PlanID.ToString();
                string tableID = "actionSteps_" + i;
                string addActionID = "addAction_" + i;
                string quarterClass = "tab-pane fade";
                string nextActionID = "nextActionID" + i;
                if (thisQ == activeQuarter) { quarterClass += " in active"; };
                <div id="@quarterID" class="@quarterClass">
                    <div>
                        @Html.Hidden("MyPlans[" + (@i) + "].Plan.PlanID", Model[i].Plan.PlanID, new { })
                        @Html.Hidden("MyPlans[" + (@i) + "].Plan.Quarter", Model[i].Plan.Quarter, new { })
                        <div class="row">
                            <div class="col-md-1">
                                @Html.LabelFor(model => model[i].Plan.Goal, htmlAttributes: new { @class = "control-label " })
                            </div>
                            <div class="col-md-10">
                                @Html.TextArea("MyPlans[" + (@i) + "].Plan.Goal", Model[i].Plan.Goal, new { rows = 2, cols = 150 })
                                @Html.ValidationMessageFor(model => model[i].Plan.Goal, "", new { @class = "text-danger" })
                            </div>
                        </div>

                    </div>
                    <div style="padding-top:12px;">
                        @{int actionNum = 0;}
                        <table id="@tableID" name="@tableID">
                            <thead>
                                <tr>
                                    <th width="40%">Action Step</th>
                                    <th width="40%">Result</th>
                                    <th width="15%">Status</th>
                                </tr>
                            </thead>
                            <tbody>

                                @foreach (HOTP.Models.tblHOTP_ActionSteps actionStep in Model[i].ActionSteps)
                                {
                                    <tr>
                                        <td class="">
                                            @Html.Hidden("MyPlans[" + (@i) + "].ActionSteps[" + actionNum + "].ActionID", actionStep.ActionID)
                                            @Html.TextArea("MyPlans[" + (@i) + "].ActionSteps[" + actionNum + "].ActionStep", actionStep.ActionStep, new { rows = 2, cols = 65 })
                                        </td>
                                        <td>
                                            @Html.TextArea("MyPlans[" + (@i) + "].ActionSteps[" + actionNum + "].Result", actionStep.Result, new { rows = 2, cols = 65 })
                                        </td>
                                        <td valign="top">
                                            @Html.DropDownList("MyPlans[" + (@i) + "].ActionSteps[" + actionNum + "].Status", new SelectList(ViewBag.PlanStatus, "Value", "Text", actionStep.Status))
                                        </td>
                                        <td valign="top">
                                            @{actionNum += 1;
                                            }
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                        <br />
                        <input type="hidden" id="@nextActionID" value="@actionNum" />
                    </div>
                </div>

            }
            @*}
                if (Model.Count > 0) } *@
        </div>
        <div style="margin-top:12px;">
            @Html.ActionLink("Back to List", "Index")
        </div>
    }


</div>

<script type="text/javascript">
    $(document).ready(function () {
        $(".noBoxStop").attr('tabindex', -1);
        $("a").click(function (e) {
            $('#loadingImage').toggle();
        });
        $("#displayForm :input").attr("disabled", true);
    });

</script>

HOTP/Views/Plan90/Details_keep.cshtml
@model HOTP.Models.tblHOTP_Plan90

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>tblHOTP_Plan90</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Quarter)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quarter)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Goal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Goal)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tblHOTP_EmployeeGoals.IndNotes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tblHOTP_EmployeeGoals.IndNotes)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.PlanID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

HOTP/Views/Plan90/Index.cshtml
@model IEnumerable<HOTP.Models.EvalViewModel>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using HOTPHelpers.Helpers

<style>
</style>

<h2>90-Day Plans</h2>

@using (Html.BeginForm(null, null, FormMethod.Post, new { id = "filterForm" }))
{
    <p>
        @Html.DropDownList("SelectedEmp", "Select an employee")
        &nbsp;&nbsp;
        @Html.DropDownList("YearEnding")
    </p>
}
<div id="theRest">
    @if (Model != null && Model.Count() > 0)
    {
        <p>
            @if (Model.First().Admin || Model.First().CanEdit)
            {
                @Html.ActionLink("Edit All", "All")                
                @:&nbsp;|&nbsp; 
            }
            @Html.ActionLink("Report All", "Report", "Plan90", new { target = "_self" } )
        </p>

    }
    @{ int totalWeight = 0;
     decimal totalItemScore = 0;
    }
    <table class="table">
        <tr>
            <th></th>
            <th></th>
            <th>
                Goal
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Goal.GoalType)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Weight)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ItemScore)
            </th>
            <th></th>
        </tr>
        @foreach (var item in Model)
        {
            totalWeight += item.Weight;
            totalItemScore += Convert.ToDecimal(item.ItemScore);
            <tr>
                <td>
                    @if (item.Admin || item.CanEdit)
                    {
                        @Html.ActionLink("Edit", "Edit", new { id = item.EmployeeGoalID })
                    }
                </td>
                <td>
                    @Html.ActionLink("Details", "Details", new { id = item.EmployeeGoalID })
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Goal.PillarGoalName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Goal.GoalType)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Weight)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ItemScore)
                </td>
            </tr>
        }
        <tr style="font-weight:bold">
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>
                @totalWeight%
            </td>
            <td>
                @totalItemScore
            </td>
        </tr>

    </table>

</div>

<script>
    document.getElementById("SelectedEmp").onchange = function () {
        $('#loadingImage').toggle();
        document.getElementById("filterForm").submit();
    };
    document.getElementById("YearEnding").onchange = function () {
        $('#loadingImage').toggle();
        document.getElementById("filterForm").submit();
    };
    $(document).ready(function () {
        if ($('#SelectedEmp').val() == "") $("#theRest").hide();
        else $("#theRest").show();
    });
</script>