HOTP/Controllers/OrgGoalsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HOTP.Models;
using System.Data.Entity.Validation;

namespace HOTP.Controllers
{
    public class OrgGoalsController : Controller
    {
        private HOTP_Entities db = new HOTP_Entities();

        // GET: Goals
        public ActionResult Index(int? SelectedKey)
        {
            string year = "";
            if (SelectedKey == null)
            {
                if (Request.QueryString["year"] == null)
                {
                    var currentYear = (db.tblHOTP_Codes.Where(w => w.CodeKey == "CurrentYear").Select(w => w.Code)).First();
                    year = currentYear.ToString();
                }
                else year = Request.QueryString["year"]; 
                try
                {
                    SelectedKey = (db.tblHOTP_Codes.Where(c => c.CodeKey == "YearEnding" && c.Code == year).Select(c => c.CodeId)).First();
                }
                catch { }
            }
            if (SelectedKey != null)
            {
                tblHOTP_Codes selected = db.tblHOTP_Codes.Find(SelectedKey);
                year = selected.Code;
                var keys = db.tblHOTP_Codes.Where(w => w.CodeKey == "YearEnding").OrderBy(q => q.Code).ToList();
                ViewBag.SelectedKey = new SelectList(keys, "CodeID", "Code", SelectedKey);
                IQueryable<tblHOTP_Goals> tblHOTP_Goals = db.tblHOTP_Goals
                    .Where(g => g.YearEnding == year && g.GoalType == "Organizational");
                //.OrderBy(d => d.Sequence);
                //var sql = tblHOTP_Goals.ToString();
                return View(tblHOTP_Goals.ToList());
            }
            else
            {
                var keys = db.tblHOTP_Codes.Where(w => w.CodeKey == "YearEnding").OrderBy(q => q.Code).ToList();
                ViewBag.SelectedKey = new SelectList(keys, "CodeID", "Code", SelectedKey);
                IQueryable<tblHOTP_Goals> tblHOTP_Goals = db.tblHOTP_Goals
                    .Where(g => g.YearEnding == "2999");
                //.OrderBy(d => d.Sequence);
                //var sql = tblHOTP_Goals.ToString();
                return View(tblHOTP_Goals.ToList());
            }

            //return View(db.tblHOTP_Goals.ToList());
        }

        // GET: Goals/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblHOTP_Goals tblHOTP_Goals = db.tblHOTP_Goals.Find(id);
            if (tblHOTP_Goals == null)
            {
                return HttpNotFound();
            }
            return View(tblHOTP_Goals); 
        }

        // GET: Goals/Create
        public ActionResult Create()
        {
            tblHOTP_Goals goal = new tblHOTP_Goals();
            goal.Rating1 = 0;
            goal.Rating2 = 0;
            goal.Rating3 = 0;
            goal.Rating4 = 0;
            goal.Rating5 = 0;
            goal.NumDecimals = 0;
            goal.Status = "Active";
            goal.GoalType = "Organizational";
            ViewBag.Pillar = PopulateCodesDDL("Pillar");
            ViewBag.YearEnding = PopulateCodesDDL("YearEnding");
            ViewBag.ResultsMeasured = PopulateCodesDDL("ResultsMeasured");
            ViewBag.BestRating = PopulateCodesDDL("BestRating");
            ViewBag.YearEndCalculation = PopulateCodesDDL("YearEndCalculation");
            ViewBag.UnitsMeasuredIn = PopulateCodesDDL("UnitsMeasuredIn");
            ViewBag.ResultsEntered = PopulateCodesDDL("ResultsEntered");
            return View(goal);
        }

        // POST: Goals/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "GoalID,YearEnding,GoalType,Pillar,GoalName,PillarGoalName,Goal,Status,ResultsMeasured,BestRating,Rating1,Rating2,Rating3,Rating4,Rating5,Rating1Suffix,Rating5Suffix,Rating2End,Rating3End,Rating4End,YearEndCalculation,UnitsMeasuredIn,NumDecimals,ResultsEntered,EnteredBy,NonEditableByLeader,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec")] tblHOTP_Goals tblHOTP_Goals)
        {
            if (ModelState.IsValid)
            {
                db.tblHOTP_Goals.Add(tblHOTP_Goals);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Pillar = PopulateCodesDDL("Pillar");
            ViewBag.YearEnding = PopulateCodesDDL("YearEnding");
            ViewBag.ResultsMeasured = PopulateCodesDDL("ResultsMeasured");
            ViewBag.BestRating = PopulateCodesDDL("BestRating");
            ViewBag.YearEndCalculation = PopulateCodesDDL("YearEndCalculation");
            ViewBag.UnitsMeasuredIn = PopulateCodesDDL("UnitsMeasuredIn");
            ViewBag.ResultsEntered = PopulateCodesDDL("ResultsEntered");
            return View(tblHOTP_Goals);
        }

        // GET: Goals/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblHOTP_Goals tblHOTP_Goals = db.tblHOTP_Goals.Find(id);
            if (tblHOTP_Goals == null)
            {
                return HttpNotFound();
            }
            ViewBag.Pillar = PopulateCodesDDL("Pillar", tblHOTP_Goals.Pillar);
            ViewBag.YearEnding = PopulateCodesDDL("YearEnding", tblHOTP_Goals.YearEnding);
            ViewBag.ResultsMeasured = PopulateCodesDDL("ResultsMeasured", tblHOTP_Goals.ResultsMeasured);
            ViewBag.BestRating = PopulateCodesDDL("BestRating", tblHOTP_Goals.BestRating);
            ViewBag.YearEndCalculation = PopulateCodesDDL("YearEndCalculation", tblHOTP_Goals.YearEndCalculation);
            ViewBag.UnitsMeasuredIn = PopulateCodesDDL("UnitsMeasuredIn", tblHOTP_Goals.UnitsMeasuredIn);
            ViewBag.ResultsEntered = PopulateCodesDDL("ResultsEntered", tblHOTP_Goals.ResultsEntered);
            return View(tblHOTP_Goals);
        }

        // POST: Goals/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "GoalID,YearEnding,GoalType,Pillar,GoalName,PillarGoalName,Goal,Status,ResultsMeasured,BestRating,Rating1,Rating2,Rating3,Rating4,Rating5,Rating1Suffix,Rating5Suffix,Rating2End,Rating3End,Rating4End,YearEndCalculation,UnitsMeasuredIn,NumDecimals,ResultsEntered,EnteredBy,NonEditableByLeader,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec")] tblHOTP_Goals tblHOTP_Goals)
        {
            var goal = db.tblHOTP_Goals.Find(tblHOTP_Goals.GoalID);
            if (goal != null)
                TryUpdateModel(goal);
            else
                return HttpNotFound();
            if (ModelState.IsValid)
            {
                db.SaveChanges();
                return RedirectToAction("Index", new { year = tblHOTP_Goals.YearEnding });
            }
            //if (ModelState.IsValid)
            //{
            //    db.Entry(tblHOTP_Goals).State = EntityState.Modified;
            //    db.SaveChanges();
            //    return RedirectToAction("Index", new { year = tblHOTP_Goals.YearEnding });
            //}
            ViewBag.Pillar = PopulateCodesDDL("Pillar", tblHOTP_Goals.Pillar);
            ViewBag.YearEnding = PopulateCodesDDL("YearEnding", tblHOTP_Goals.YearEnding);
            ViewBag.ResultsMeasured = PopulateCodesDDL("ResultsMeasured", tblHOTP_Goals.ResultsMeasured);
            ViewBag.BestRating = PopulateCodesDDL("BestRating", tblHOTP_Goals.BestRating);
            ViewBag.YearEndCalculation = PopulateCodesDDL("YearEndCalculation", tblHOTP_Goals.YearEndCalculation);
            ViewBag.UnitsMeasuredIn = PopulateCodesDDL("UnitsMeasuredIn", tblHOTP_Goals.UnitsMeasuredIn);
            ViewBag.ResultsEntered = PopulateCodesDDL("ResultsEntered", tblHOTP_Goals.ResultsEntered);

            return View(tblHOTP_Goals);
        }

        // GET: Goals/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblHOTP_Goals tblHOTP_Goals = db.tblHOTP_Goals.Find(id);
            if (tblHOTP_Goals == null)
            {
                return HttpNotFound();
            }
            return View(tblHOTP_Goals);
        }

        // POST: Goals/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            tblHOTP_Goals tblHOTP_Goals = db.tblHOTP_Goals.Find(id);
            db.tblHOTP_Goals.Remove(tblHOTP_Goals);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        private SelectList PopulateCodesDDL(string codeKey, object selectedCode = null)
        {
            var codeQuery = from p in db.tblHOTP_Codes
                               where p.CodeKey == codeKey
                               orderby p.Sequence
                               select p;
            SelectList sl = new SelectList(codeQuery, "Code", "Code", selectedCode);
            return sl;
        }

        // GET: Goals/Cascade
        [HttpGet]
        public ActionResult Cascade()
        {

HOTP/Views/OrgGoals/Cascade.cshtml
@model  HOTP.Models.CascadeGoals

@{
    ViewBag.Title = "All";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using HOTPHelpers.Helpers

<style>
     .weightInput input {
        width: 40px;
    }
     .table td {
         font-size:12px;
     }
</style>
<h2>Organizational Goals</h2>
<h4>Assign to Employees</h4>

@using (Html.BeginForm("Cascade", "OrgGoals", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    
    <table class="table">
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th></th>
            @foreach (var course in Model.Goals)
            {
                <th>
                    @Html.DisplayFor(modelItem => course.PillarGoalName)
                </th>
            }
            <th>Total</th>
        </tr>

        @for (int i = 0; i < Model.Employees.Count; i++)
        {
            <tr>
                <td >
                    @Html.Hidden("MyEmps", (@i))
                    @Html.TextBox("MyEmps.EmployeeID", Model.Employees[i].EmployeeID, new { @class = "noBox", @readonly = "readonly", @tabindex=-1 })
                </td>
                <td class="noBox">
                    @Html.TextBox("MyEmps[" + (@i) + "].LastName", Model.Employees[i].LastName + ", " + Model.Employees[i].FirstName,
                     new { @class = "noBox", @readonly = "readonly", @tabindex = -1 })
                </td>
                <td class="noBox">Weights:</td>
                @for (int g = 0; g < Model.Goals.Count; g++)
                {
                    <td class="weightInput">
                        @Html.Hidden("MyGoals", (@g))
                        @Html.Hidden("MyGoals_" + @i + "[" + (@g) + "].GoalID", Model.Goals[g].GoalID)
                        @Html.TextBox("MyGoals_" + Model.Employees[i].EmployeeID + "_" + Model.Goals[g].GoalID + "_Weight",
                              MyHTMLHelpers.GetWeight(Model.Employees[i].EmployeeID, Model.Goals[g].GoalID), new { @class = "weight" })%
                    </td>
                }
                <td></td>
            </tr>
        }

        <tr>
            <td colspan="4">
                <input type="submit" value="Save" class="btn btn-default" />
                &nbsp;
                @Html.ActionLink("Back to List (don't save)", "Index", new { year = Html.DisplayFor(modelItem => Model.Goals[1].YearEnding) })
            </td>
        </tr>
    </table>
}

<script type="text/javascript">
    $(document).ready(function () {
        $(".weight").keypress(function (event) {
            if ((event.which < 48 || event.which > 57)) {
                event.preventDefault();
            }
        });
    });

function isNumberKey(evt)
{
          var charCode = (evt.which) ? evt.which : event.keyCode;
          if (charCode != 46 && charCode > 31
            && (charCode < 48 || charCode > 57))
             return false;

          return true;
}
</script>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HOTP/Views/OrgGoals/Delete.cshtml
@model HOTP.Models.tblHOTP_Goals

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Organizational Goals</h2>
<h4>Delete</h4>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>tblHOTP_Goals</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.YearEnding)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.YearEnding)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Pillar)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pillar)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GoalName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GoalName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PillarGoalName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PillarGoalName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Goal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Goal)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ResultsMeasured)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ResultsMeasured)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BestRating)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BestRating)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Rating1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Rating1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Rating2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Rating2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Rating3)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Rating3)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Rating4)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Rating4)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Rating5)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Rating5)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.YearEndCalculation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.YearEndCalculation)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UnitsMeasuredIn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UnitsMeasuredIn)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NumDecimals)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NumDecimals)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ResultsEntered)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ResultsEntered)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EnteredBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EnteredBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NonEditableByLeader)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NonEditableByLeader)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Jan)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Jan)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Feb)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Feb)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Mar)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Mar)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Apr)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Apr)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.May)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.May)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Jun)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Jun)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Jul)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Jul)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Aug)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Aug)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sep)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sep)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Oct)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Oct)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nov)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nov)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Dec)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Dec)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List (don't save)", "Index", new { year = Html.DisplayFor(modelItem => Model.YearEnding) })
        </div>
    }
</div>

HOTP/Views/OrgGoals/Scores.cshtml
@model List<HOTP.Models.tblHOTP_Goals>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    select {
        font-size: medium;
    }

    .noBox {
        border: none 0px;
    }

    .weightInput input {
        width: 35px;
    }

    .score {
        width: 35px;
    }
    .rating {
        width: 25px;
        margin: 0px 0px 0px 0px;
        padding:0px 0px 0px 0px;
        background-color: #DCECEF;
        vertical-align: baseline;
    }
    #ratingTable td {
        border-top:none 0px;
        margin:0px 0px 0px 0px;
        padding:0px 0px 0px 0px;
    }
    .writeTrue {
    }
    .writeFalse, .Org {
        width: 35px;
        background-color: #DCECEF;
    }

    .writeFalse2 {
        width: 55px;
        background-color: #DCECEF;
    }

    .white {
        background-color: white;
    }

    .myLabel {
        font-weight:bold;
    }

    .Individual {
        width: 35px;
    }
    .ratingNum {
        font-size:large;
        font-weight:bold;
        padding-left:8px;
        padding-right:4px;
    }
</style>

<h2>Organizational Goals</h2>
<h4>Enter Scores</h4>

@*@using (Html.BeginForm(null, null, FormMethod.Get, new { id = "filterForm" }))
    {
        <p>
            @Html.DropDownList("SelectedKey", "Select a year")
            &nbsp;&nbsp;
        </p>
    }*@

@using (Html.BeginForm("Scores", "OrgGoals", FormMethod.Post))
{
    <input type="hidden" id="scoreFrom" value="Scores" />
    <table class="table">
        @for (int i = 0; i < Model.Count; i++)
        {
            <tr>
                <td>
                    <div class="row">
                        <div class="col-md-8">
                            @Html.Hidden("MyGoals.Index", (@i))
                            @Html.Hidden("MyGoals[" + (@i) + "].GoalID", Model[i].GoalID)
                            <div class="img-rounded" style="font-size:large;background-color:#034f5a; color:white; font-weight:bolder; text-align:left; padding:4px 4px 4px 4px;">
                                &nbsp;
                                @Html.DisplayFor(modelItem => Model[i].PillarGoalName)
                            </div>
                            <div class=" text-info" style="font-size:medium;">
                                @Html.DisplayFor(modelItem => Model[i].Goal)
                            </div>
                            <div class="row">
                                <div class="col-md-1">
                                    Jan<br />
                                    @Html.TextBox("MyGoals[" + (@i) + "].JanScore", Model[i].JanScore, new { @class = "score write" + Model[i].Jan })
                                </div>
                                <div class="col-md-1">
                                    Feb<br />
                                    @Html.TextBox("MyGoals[" + (@i) + "].FebScore", Model[i].FebScore, new { @class = "score write" + Model[i].Feb })
                                </div>
                                <div class="col-md-1">
                                    Mar<br />
                                    @Html.TextBox("MyGoals[" + (@i) + "].MarScore", Model[i].MarScore, new { @class = "score write" + Model[i].Mar })
                                </div>
                                <div class="col-md-1">
                                    Apr<br />
                                    @Html.TextBox("MyGoals[" + (@i) + "].AprScore", Model[i].AprScore, new { @class = "score write" + Model[i].Apr })
                                </div>
                                <div class="col-md-1">
                                    May<br />
                                    @Html.TextBox("MyGoals[" + (@i) + "].MayScore", Model[i].MayScore, new { @class = "score write" + Model[i].May })
                                </div>
                                <div class="col-md-1">
                                    Jun<br />
                                    @Html.TextBox("MyGoals[" + (@i) + "].JunScore", Model[i].JunScore, new { @class = "score write" + Model[i].Jun })
                                </div>
                                <div class="col-md-1">
                                    Jul<br />
                                    @Html.TextBox("MyGoals[" + (@i) + "].JulScore", Model[i].JulScore, new { @class = "score write" + Model[i].Jul })
                                </div>
                                <div class="col-md-1">
                                    Aug<br />
                                    @Html.TextBox("MyGoals[" + (@i) + "].AugScore", Model[i].AugScore, new { @class = "score write" + Model[i].Aug })
                                </div>
                                <div class="col-md-1">
                                    Sep<br />
                                    @Html.TextBox("MyGoals[" + (@i) + "].SepScore", Model[i].SepScore, new { @class = "score write" + Model[i].Sep })
                                </div>
                                <div class="col-md-1">
                                    Oct<br />
                                    @Html.TextBox("MyGoals[" + (@i) + "].OctScore", Model[i].OctScore, new { @class = "score write" + Model[i].Oct })
                                </div>
                                <div class="col-md-1">
                                    Nov<br />
                                    @Html.TextBox("MyGoals[" + (@i) + "].NovScore", Model[i].NovScore, new { @class = "score write" + Model[i].Nov })
                                </div>
                                <div class="col-md-1">
                                    Dec<br />
                                    @Html.TextBox("MyGoals[" + (@i) + "].DecScore", Model[i].DecScore, new { @class = "score write" + Model[i].Dec })
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4 ">
                            <div class="row">
                                <div class="col-md-6 pull-right">
                                    @Html.Hidden("MyGoals[" + (@i) + "].BestRating", Model[i].BestRating)
                                    @Html.Hidden("MyGoals[" + (@i) + "].NumDecimals", Model[i].NumDecimals)
                                    @Html.Hidden("MyGoals[" + (@i) + "].YearEnding", Model[i].YearEnding)
                                    Calculation: @Html.TextBox("MyGoals[" + (@i) + "].YearEndCalculation", Model[i].YearEndCalculation, new { @class = "noBox writeFalse2 white myLabel", @readonly = "readonly" })<br />
                                    Result: @Html.TextBox("MyGoals[" + (@i) + "].Result", Model[i].Result, new { @class = "noBox writeFalse2 white myLabel", @readonly="readonly" })<br />
                                    Score: @Html.TextBox("MyGoals[" + (@i) + "].Score", Model[i].Score, new { @class = "noBox writeFalse2 white myLabel", @readonly = "readonly" })<br />
                                </div>
                                <div class="col-md-6">
                                    <table id="ratingTable" class="img-rounded pull-right" style="background-color:#DCECEF; width:180px; ">
                                        <tr>
                                            <td><span class="ratingNum">5</span>  is</td>
                                            <td>
                                                @Html.TextBox("MyGoals[" + (@i) + "].Rating5", Model[i].Rating5, new { @class = "rating noBox writeFalse", @readonly = "true" })
                                            </td>
                                            <td>
                                                @Model[i].Rating5Suffix
                                            </td>
                                        </tr>
                                        <tr>
                                            <td><span class="ratingNum">4</span>  is</td>
                                            <td>
                                                @Html.TextBox("MyGoals[" + (@i) + "].Rating4", Model[i].Rating4, new { @class = "rating noBox writeFalse", @readonly = "true" })
                                            </td>
                                            <td>
                                                to @Model[i].Rating4End
                                            </td>
                                        </tr>
                                        <tr>
                                            <td><span class="ratingNum">3</span>  is</td>
                                            <td>
                                                @Html.TextBox("MyGoals[" + (@i) + "].Rating3", Model[i].Rating3, new { @class = "rating noBox writeFalse", @readonly = "true" })
                                            </td>
                                            <td>
                                                to @Model[i].Rating3End
                                            </td>
                                        </tr>
                                        <tr>
                                            <td><span class="ratingNum">2</span>  is</td>
                                            <td>
                                                @Html.TextBox("MyGoals[" + (@i) + "].Rating2", Model[i].Rating2, new { @class = "rating noBox writeFalse", @readonly = "true" })
                                            </td>
                                            <td>
                                                to @Model[i].Rating2End
                                            </td>
                                        </tr>
                                        <tr>
                                            <td><span class="ratingNum">1</span>  is</td>
                                            <td>
                                                @Html.TextBox("MyGoals[" + (@i) + "].Rating1", Model[i].Rating1, new { @class = "rating noBox writeFalse", @readonly = "true" })
                                            </td>
                                            <td>
                                                @Model[i].Rating1Suffix
                                            </td>
                                        </tr>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </td>
            </tr>
        }
        @if (Model.Count > 0)
        {
            <tr>
                <td>
                    <button type="submit" value="Save" name="save" class="btn btn-primary">
                        Save
                    </button>
                    &nbsp;
                    @Html.ActionLink("Back to List (don't save)", "Index", new { year = Html.DisplayFor(modelItem => Model[1].YearEnding) })
                </td>
            </tr>
        }
    </table>

}

<script type="text/javascript">

</script>

<script src="~/Scripts/scoreCalc.js"></script>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}